#!/bin/bash
# nginx - this script starts and stops the nginx daemon
#
# chkconfig:   2345 85 15
# description:  NGINX is an HTTP(S) server, HTTP(S) reverse \
#               proxy and IMAP/POP3 proxy server
# processname: nginx
# config:      /usr/local/nginx/conf/nginx.conf
# pidfile:     /var/run/nginx.pid
# lockfile:     /var/lock/subsys/nginx

# Source function library.
. /etc/rc.d/init.d/functions

NGINX_HOME="/usr/local/nginx"
NGINX_EXEC="${NGINX_HOME}/sbin/nginx"
#NGINX_EXEC_USER="nginx"
NGINX_CONFIG="${NGINX_HOME}/conf/nginx.conf"

prog=$(basename ${NGINX_EXEC})

lockfile=/var/lock/subsys/nginx

start() {
    [ -x ${NGINX_EXEC} ] || exit 5
    [ -f ${NGINX_CONFIG} ] || exit 6
    echo -n $"Starting $prog: "
    #daemon --user=${NGINX_EXEC_USER} ${NGINX_EXEC} -c ${NGINX_CONFIG}
    daemon ${NGINX_EXEC} -c ${NGINX_CONFIG}
    retval=$?
    echo
    [ $retval -eq 0 ] && touch $lockfile
    return $retval
}

stop() {
    echo -n $"Stopping $prog: "
    killproc $prog -QUIT
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
    return $retval
}

restart() {
    configtest || return $?
    stop
    sleep 1
    start
}

reload() {
    configtest || return $?
    echo -n $"Reloading $prog: "
    killproc ${NGINX_EXEC} -HUP
    RETVAL=$?
    echo
}

force_reload() {
    restart
}

configtest() {
  ${NGINX_EXEC} -t -c ${NGINX_CONFIG}
}

rh_status() {
    status $prog
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}

case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
        rh_status_q || exit 0
        $1
        ;;
    restart|configtest)
        $1
        ;;
    reload)
        rh_status_q || exit 7
        $1
        ;;
    force-reload)
        force_reload
        ;;
    status)
        rh_status
        ;;
    condrestart|try-restart)
        rh_status_q || exit 0
            ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload|configtest}"
        exit 2
esac
exit $?
