#!/bin/bash
# tomcat - this script starts and stops the tomcat daemon
#
# chkconfig:   2345 85 15
# description: Tomcat 
# processname: java
# config:      /usr/local/var/tomcat/conf/server.xml
# pidfile:     /var/run/tomcat/tomcat.pid
# lockfile:     /var/lock/subsys/tomcat
# Source function library.
. /etc/rc.d/init.d/functions

CATALINA_BASE="/usr/local/var/tomcat"
CATALINA_STARTUP="${CATALINA_BASE}/bin/startup.sh"
CATALINA_SHUTDOWN="${CATALINA_BASE}/bin/shutdown.sh"
CATALINA_USER="tomcat"

prog="tomcat"

lockfile=/var/lock/subsys/$prog

if [ ! -e /var/run/$prog ]; then
  mkdir -p /var/run/$prog
  chown -R ${CATALINA_USER}:${CATALINA_USER} /var/run/$prog
fi

start() {
    [ -x ${CATALINA_STARTUP} ] || exit 5
    echo -n $"Starting $prog: "
    daemon --user=${CATALINA_USER} ${CATALINA_STARTUP}
    #daemon ${CATALINA_STARTUP}
    retval=$?
    echo
    [ $retval -eq 0 ] && touch $lockfile
    return $retval
}

stop() {
    echo -n $"Stopping $prog: "
    #killproc $prog -QUIT
    /bin/bash ${CATALINA_SHUTDOWN}
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
    return $retval
}

restart() {
    configtest || return $?
    stop
    sleep 1
    start
}

reload() {
    configtest || return $?
    echo -n $"Reloading $prog: "
    killproc ${NGINX_EXEC} -HUP
    RETVAL=$?
    echo
}

force_reload() {
    restart
}

configtest() {
  ${NGINX_EXEC} -t -c ${NGINX_CONFIG}
}

rh_status() {
    status $prog
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}

case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
        rh_status_q || exit 0
        $1
        ;;
    restart|configtest)
        $1
        ;;
    reload)
        rh_status_q || exit 7
        $1
        ;;
    force-reload)
        force_reload
        ;;
    status)
        rh_status
        ;;
    condrestart|try-restart)
        rh_status_q || exit 0
            ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload|configtest}"
        exit 2
esac
exit $?
